[project]
name = "alchemark-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.3",
    "pymupdf>=1.25.5",
    "pymupdf4llm>=0.0.21",
    "tiktoken>=0.9.0",
]
